services:
  - type: web
    name: s3-like-object-storage
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
